### ISSUE TITLE
Font Awesome library

### ISSUE THREAD

**Issue by timurtripp** [CuBoulder/ucb_ckeditor_plugins#26]
Right now the plan is to embed the library directly into the module and include it on the pages we need. However, the module library may conflict with the theme library, at the very least it's redundant to include the Font Awesome library twice. @jnicholCU any thoughts on this?

**Comment by TeddyBearX** [comment]
In my dev environment I'm not including the library but instead using the one added by the Font Awesome contrib module. We need to figure out how to handle this for prod though.

**Comment by timurtripp** [comment]
Issue closed with any relevant discussion now in CuBoulder/tiamat-theme#483
