### ISSUE TITLE
CKEditor 5 plugin: Blockquote

### ISSUE THREAD

**Issue by jnicholCU** [CuBoulder/ucb_ckeditor_plugins#40]
There's still a number of shortcodes from Drupal 7 Express that need to be implemented. Below are the remaining shortcodes and descriptions of how they work. Most shortcodes, unless specified, come from the cu_shortcodes module: https://github.com/CuBoulder/express_mono/blob/dev/modules/custom/cu_shortcodes

Blockquote
Provides a more styled blockquote with the options of floating, font style, and an icon.
[blockquote icon="fa-quote-left , or any font awesome icon class" style="serif/sans-serif"]your content here[/blockquote]

**Comment by timurtripp** [comment]
An icon can be placed inside a blockquote using the icon plugin. Is it just the style we're missing?

**Comment by timurtripp** [comment]
Wondering if we have enough of the functionality covered to close this one out or not.

**Comment by jnicholCU** [comment]
That's a good question. Probably need to bring @jcsparks in on that though. While ideally we can create the same effect with what we have I'm not sure that will fly for the ui team.

**Comment by timurtripp** [comment]
We're going to use the CKEditor 5 built-in blockquote and strip the extra stuff. Marking as not planned.
