### ISSUE TITLE
CSS Specificity of Box <a> tag styles overrides Button's text color, when placed in a Box

### ISSUE THREAD

**Issue by patrickbrown-io** [CuBoulder/ucb_ckeditor_plugins#55]
Conflicting styles with Box's `<a>` style specificity: (0,5,1):

```
.ucb-box.ucb-box-theme-lightgray.ucb-box-style-fill a:visited:not(:hover,:active,:focus) {
    color: #01579B;
}
```

and Buttons specificity: (0,2,0)

```
.ucb-link-button.ucb-link-button-blue {
    color: #fff; # Gets overwritten
    background-color: #0277BD;
}
```
Results in Button text color getting overwritten, as shown (light grey box with Blue Buttons, text should be white):
<img width="376" alt="Screenshot 2024-03-07 at 9 54 01 AM" src="https://github.com/CuBoulder/ucb_ckeditor_plugins/assets/85851903/ef3bb4f2-0e10-4d99-b3f4-c97fe89406d3">

Seems like you can just add  `color: #fff !important` to the Button styles. Will need to test as this affects pages like the Issue where they build a menu in the body out of the Box and Button, and Icon plugins

**Comment by timurtripp** [comment]
`!important` is a workable solution to override styles from box or other places. I also noticed text color issues for buttons placed in the site contact info footer block.

**Comment by timurtripp** [comment]
You can also try adding `:link` and `:visited` to button text color styles if you want to avoid adding `!important` (I generally try to avoid it when possible).
