### ISSUE TITLE
Campus map URLs changed and have broken the embed

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/ucb_ckeditor_plugins#64]
At some point in the last few years it looks like the URLs to specific locations on the map have changed and they don't work with the map embed plugin.

The old pattern looked like this: https://www.colorado.edu/map/?id=336#!m/193996

But the new url looks like this: https://www.colorado.edu/map?id=336#!ct/68796,68797,68838,68840,68841,68843,69772,21218,2732,2733,2734,2737,20810,20986,63561,63563,65036?m/193996?s/vis?mc/40.00753799999998,-105.27047700000003?z/19?lvl/0?share

While the original URL patterns still work, it doesn't seem possible to get a url matching that pattern via the map interface.

**Comment by timurtripp** [comment]
This must be a change they made recently, it was still using the old URL when I developed the plugin.

**Comment by timurtripp** [comment]
`m` value is still all that's needed. Just need to filter out the other junk they added which seems to be intended to preserve things we don't care about like what someone typed into the search box.
