### ISSUE TITLE
CKEditor 5 Plugin: Columns

### ISSUE THREAD

**Issue by jcsparks** [CuBoulder/ucb_ckeditor_plugins#75]
Need to add in a plugin to be able to break pieces of content up into columns.

**Comment by jcsparks** [comment]
This may be better served as a template rather than a plugin : https://ckeditor.com/docs/ckeditor5/latest/features/template.html

**Comment by jcsparks** [comment]
Template is apparently a premium feature : 

To use this premium feature, you need to activate it with proper credentials. Refer to the [License key and activation](https://ckeditor.com/docs/ckeditor5/latest/support/licensing/license-key-and-activation.html) guide for details.

**Comment by timurtripp** [comment]
Investigate https://www.drupal.org/project/ckeditor_bs_grid

**Comment by timurtripp** [comment]
@patrickbrown-io Building our own plugin but only allowing even columns without additional options is fine.
