### ISSUE TITLE
Box Plugin HTML Filter

### ISSUE THREAD

**Issue by jcsparks** [CuBoulder/ucb_ckeditor_plugins#96]
We need to have the ability to add inline color styles for the Box on the Alerts site.  Currently the box plugin is filtering out any inline styles and removing these when they're added.  

Please modify the plugin to not filter out these styles so we can add custom colors to blocks on the Alerts site.

**Comment by timurtripp** [comment]
Going to call this a bug since I did on CKEditor 5 Icons and those classes should be preserved since they were explicitly allowed in styles. Same fix will work here but the catch is the class has to be manually added from the source mode.
